services:
  wordpress:
    build: ./
    container_name: wordpress
    restart: always
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./caddy/caddy_data:/data
      - ./caddy/caddy_config:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./wordpress/html:/var/www/html

  db:
    image: mariadb:10.11
    container_name: db
    env_file: .env
    restart: always
    volumes:
      - ./wordpress/mysql:/var/lib/mysql
      - ./wordpress/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf
